name: Convert
run-name: Converting mods
on: [
    push
]
jobs:
    convert:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: |
                echo "<debug>"
                for file in ./src/*
                do
                    echo $file
                    tar czf zip/$file.tar.gz $file
                done
                echo "</debug>"
                ls ./zip

