name: Convert
run-name: Converting mods
on: 
    push:
        paths:
            - src/**

permissions:
    contents: write
jobs:
    convert:
        runs-on: ubuntu-latest
        steps:        
            - uses: actions/checkout@v4
            - run: |
                for file in ./src/*
                do
                    zip -r ${file}.zip ${file}
                    mv ${file}.zip zip
                done
                git pull
                git add ./zip/*
            - run: |
                git config user.name "cool-test"
                git config user.email "nathan.watson.172@gmail.com"
                git commit -m "Cool Test!!!!!!!!!!"
                git push

