name: Convert
run-name: Converting mods
on: [
    push
]
jobs:
    convert:
        runs-on: ubuntu-latest
        steps:
            - run: |
                git config user.name "cool-test"
                git config user.email "nathan.watson.172@gmail.com"

            - uses: actions/checkout@v4
            - run: |
                echo "<debug>"
                for file in ./src/*
                do
                    echo $file
                    tar czf ${file}.tar.gz ${file}
                    mv ${file} zip
                done
                echo "</debug>"
                ls ./zip
                
                git add ./zip/*
                git commit -m "Cool Test!!!!!!!!!!"

